{% set version = '0.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-chromote
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/chromote_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/chromote/chromote_{{ version }}.tar.gz
  sha256: f89427addeb2a990906a2ef541d2690ac69de91ec38a094feb4560b6ada64929

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-curl
    - r-fastmap
    - r-jsonlite
    - r-later >=1.1.0
    - r-magrittr
    - r-processx
    - r-promises >=1.1.1
    - r-rlang
    - r-websocket >=1.2.0
  run:
    - r-base
    - r-r6
    - r-curl
    - r-fastmap
    - r-jsonlite
    - r-later >=1.1.0
    - r-magrittr
    - r-processx
    - r-promises >=1.1.1
    - r-rlang
    - r-websocket >=1.2.0

test:
  commands:
    - $R -e "library('chromote')"           # [not win]
    - "\"%R%\" -e \"library('chromote')\""  # [win]

about:
  home: https://github.com/rstudio/chromote
  license: GPL-2.0-or-later
  summary: An implementation of the 'Chrome DevTools Protocol', for controlling a headless Chrome
    web browser.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - jdblischak

# Package: chromote
# Title: Headless Chrome Web Browser Interface
# Version: 0.1.1
# Authors@R: c( person("Winston", "Chang", role = c("aut", "cre"), email = "winston@rstudio.com"), person("Barret", "Schloerke", role = c("aut"), email = "barret@rstudio.com"), person(given = "RStudio", role = c("cph", "fnd")) )
# Description: An implementation of the 'Chrome DevTools Protocol', for controlling a headless Chrome web browser.
# License: GPL-2
# Encoding: UTF-8
# SystemRequirements: Google Chrome or other Chromium-based browser. chromium: chromium (rpm) or chromium-browser (deb)
# Imports: curl, jsonlite, websocket (>= 1.2.0), processx, R6, later (>= 1.1.0), promises (>= 1.1.1), magrittr, rlang, fastmap
# Suggests: testthat (>= 3.0.0), showimage
# RoxygenNote: 7.2.1
# URL: https://github.com/rstudio/chromote
# BugReports: https://github.com/rstudio/chromote/issues
# Config/testthat/edition: 3
# Config/Needs/website: tidyverse/tidytemplate
# Language: en-US
# NeedsCompilation: no
# Packaged: 2022-09-07 13:27:44 UTC; barret
# Author: Winston Chang [aut, cre], Barret Schloerke [aut], RStudio [cph, fnd]
# Maintainer: Winston Chang <winston@rstudio.com>
# Repository: CRAN
# Date/Publication: 2022-09-07 14:10:02 UTC
